### ISSUE TITLE
VimCmdHandler: edit_file

### ISSUE THREAD

**Issue by extsoft** [ivan-podorozhnyi/ssh_tasks#10]
Looks like instead of this method, we need to have a separate abstraction (like Command) which is able to send some commands to given connection (like `MyCommand(...).execute(connection)`).

**Comment by ivan-podorozhnyi** [comment]
@extsoft It seems that this issue is not actual anymore. Do you think that we must implement some other abstraction to run vim commands?
At this moment our tests look like:
```
def test_edit_vim(connection, sftp):
    txt_file = TxtFile('new_file')
    remote_file = RemoteHomeFile(txt_file, 'ivan')
    random_text = RandomGenerator(10).generate_string('digits')
    vim_handler = VimCmdHandler(connection)
    vim_handler.edit_file(txt_file.name(), random_text)
    remote_file = sftp.open(remote_file.name())
    file_content = ''
    for line in remote_file:
        file_content += line
    assert random_text in file_content

```
