### ISSUE TITLE
connection.py module: upgrade Connection

### ISSUE THREAD

**Issue by extsoft** [ivan-podorozhnyi/ssh_tasks#11]
The `Connection` class isn't used in the code. But there are two different connections within this module:
Shell and SFTP. Based on this, I can suggest:
1. `Connection` class will be responsible for establishing on an appropriate connection, command executions, disconnecting (`ShellCmdHandler:send_command` and `ShellCmdHandler:read_output` from `cmd_handler.py` need to be used here).
2. `ShellConnection` will implement such behavior for interactive shell session.
3. `SftpConnection` will implement such behavior for interactive FTPS session.
4. If you implement this, then you could `ShellCmdHandler` from `cmd_handler.py`.

**Comment by AntonKarabaza** [comment]
@extsoft 
As I understand, we have to create such structure:
```
    class Connection:
         @abstract
         connect():
             pass
         @abstract
         send_command():
             pass
         @abstract
         disconnect():
             pass

    class ShellConnection(Connection):
          pass

    class SftpConnection(Connection):
          pass
```
But if we create such structure, we will have in each connection type their own `SSHClient` from `paramiko`. Now we are working within one `SSHClient` but in different channels for interactive shell and sftp. Is it rational to do this, to have separate `SSHClients`?
Or we have to pass `SSHClient` as a parameter to our constructors of `ShellConnection` and `SftpConnection` classes. Do we need some another abstraction for this `SSHClient` then? Or it will be ok to create it, for example, in `conftest.py` in `connection` fixture, pass it to required classes and then close in `tear_down`?

**Comment by extsoft** [comment]
@AntonKarabaza you are right about the structure. 

> Now we are working within one SSHClient but in different channels for interactive shell and sftp. Is it rational to do this, to have separate SSHClients?

I'm not interested in implementation details. I would expect that Shell or Sftp will execute some commands. 

> Or we have to pass SSHClient as a parameter to our constructors of ShellConnection and SftpConnection classes. Do we need some another abstraction for this SSHClient then? Or it will be ok to create it, for example, in conftest.py in connection fixture, pass it to required classes and then close in tear_down?

It's up to you. Let's do some implementation and then discuss.
